server:
  port: 8888
  servlet:
    context-path: /general

spring:
  profiles:
    active: dev
  application:
    name: general-support
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    # 数据源使用 TODO 对比不同的主流数据源连接
    type: com.alibaba.druid.pool.DruidDataSource

# ORM 配置 TODO 对比不同的主流 ORM
mybatis:
  mapper-locations: classpath:mybatis-mappers/*.xml
  config-location: classpath:mybatis-config.xml



