server:
  port: 8888
  servlet:
    context-path: /general

spring:
  profiles:
    active: dev
  application:
    name: general-support
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    # 数据源使用 TODO 对比不同的主流数据源连接
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:db/table-data.sql
    url: jdbc:mysql://localhost:3306/general?characterEncoding=UTF8
    data: classpath:db/data.sql
    username: root
    password: root

mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml



